[package]
name = "nib-test"
version = "0.1.0"
edition = "2024"
description = "A test runner for Nib tests"

[dependencies]
clap = { version = "4.5.43", features = ["derive"] }
nib-core = { version = "0.0.1", path = "../nib-core" }
