name: Nib CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        config:
          - os: ubuntu-latest 
          - os: windows-latest
    runs-on: ${{ matrix.config.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run unit tests
      run: cargo test --verbose
    - name: Run Nib tests
      run: cargo run -p nib-test -- nib-test/testcases